#include <stdio.h>
#include <stdlib.h>

/* func decls begin */
/* func decls end */

  /* Ast::Scope prog: 3 symbols, 1 children */
  int a[144];
  int b[144];
  char str[27] = "The sampled element is %d\n";

int main (){
    /* Ast::Block main body: 111 symbols, 175 children */
    int var_retval;
    int var_i;
    int var_j;
    int var_reg2mem_alloca_point;
    int var_0;
    int var_cmp;
    int var_1;
    int var_cmp2;
    int var_2;
    double var_conv;
    double var_add;
    int var_3;
    double var_conv4;
    double var_add5;
    int var_conv6;
    int var_4;
    int var_5;
    int var_mul;
    int var_add7;
    long long var_idxprom;
    int *var_arrayidx;
    int var_6;
    double var_conv8;
    double var_add9;
    int var_7;
    double var_conv10;
    double var_add11;
    int var_conv12;
    int var_8;
    int var_9;
    int var_mul13;
    int var_add14;
    long long var_idxprom15;
    int *var_arrayidx16;
    int var_10;
    int var_inc;
    int var_11;
    int var_inc18;
    int var_12;
    int var_cmp21;
    int var_13;
    int var_cmp25;
    int var_14;
    int var_sub;
    int var_15;
    int var_mul28;
    int var_add29;
    long long var_idxprom30;
    int *var_arrayidx31;
    int var_16;
    int var_17;
    int var_add32;
    int var_18;
    int var_mul33;
    int var_add34;
    long long var_idxprom35;
    int *var_arrayidx36;
    int var_19;
    int var_add37;
    int var_20;
    int var_21;
    int var_add38;
    int var_sub39;
    long long var_idxprom40;
    int *var_arrayidx41;
    int var_22;
    int var_add42;
    int var_23;
    int var_24;
    int var_add43;
    int var_add44;
    long long var_idxprom45;
    int *var_arrayidx46;
    int var_25;
    int var_add47;
    double var_conv48;
    double var_mul49;
    int var_conv50;
    int var_26;
    int var_27;
    int var_mul51;
    int var_add52;
    long long var_idxprom53;
    int *var_arrayidx54;
    int var_28;
    int var_inc56;
    int var_29;
    int var_inc59;
    int var_30;
    int var_cmp62;
    int var_31;
    int var_cmp66;
    int var_32;
    int var_33;
    int var_mul69;
    int var_add70;
    long long var_idxprom71;
    int *var_arrayidx72;
    int var_34;
    int var_35;
    int var_36;
    int var_mul73;
    int var_add74;
    long long var_idxprom75;
    int *var_arrayidx76;
    int var_37;
    int var_inc78;
    int var_38;
    int var_inc81;
    int var_39;
    int var_call;

    lbl_entry:;
    var_reg2mem_alloca_point = 0;
    var_retval = 0;
    var_i = 0;
    goto lbl_for_cond;
    lbl_for_cond:;
    var_0 = var_i;
    var_cmp = (var_0 < 12);
    if (var_cmp) goto lbl_for_body; else goto lbl_for_end19;
    lbl_for_body:;
    var_j = 0;
    goto lbl_for_cond1;
    lbl_for_cond1:;
    var_1 = var_j;
    var_cmp2 = (var_1 < 12);
    if (var_cmp2) goto lbl_for_body3; else goto lbl_for_end;
    lbl_for_body3:;
    var_2 = var_i;
    var_conv = var_2;
    var_add = (12.0 + var_conv);
    var_3 = var_j;
    var_conv4 = var_3;
    var_add5 = (var_add + var_conv4);
    var_conv6 = var_add5;
    var_4 = var_j;
    var_5 = var_i;
    var_mul = (var_5 * 12);
    var_add7 = (var_4 + var_mul);
    var_idxprom = var_add7;
    var_arrayidx = (& a[var_idxprom]);
    *var_arrayidx = var_conv6;
    var_6 = var_i;
    var_conv8 = var_6;
    var_add9 = (12.0 + var_conv8);
    var_7 = var_j;
    var_conv10 = var_7;
    var_add11 = (var_add9 + var_conv10);
    var_conv12 = var_add11;
    var_8 = var_j;
    var_9 = var_i;
    var_mul13 = (var_9 * 12);
    var_add14 = (var_8 + var_mul13);
    var_idxprom15 = var_add14;
    var_arrayidx16 = (& b[var_idxprom15]);
    *var_arrayidx16 = var_conv12;
    goto lbl_for_inc;
    lbl_for_inc:;
    var_10 = var_j;
    var_inc = (var_10 + 1);
    var_j = var_inc;
    goto lbl_for_cond1;
    lbl_for_end:;
    goto lbl_for_inc17;
    lbl_for_inc17:;
    var_11 = var_i;
    var_inc18 = (var_11 + 1);
    var_i = var_inc18;
    goto lbl_for_cond;
    lbl_for_end19:;
    var_i = 0;
    goto lbl_for_cond20;
    lbl_for_cond20:;
    var_12 = var_i;
    var_cmp21 = (var_12 < 11);
    if (var_cmp21) goto lbl_for_body23; else goto lbl_for_end60;
    lbl_for_body23:;
    var_j = 0;
    goto lbl_for_cond24;
    lbl_for_cond24:;
    var_13 = var_j;
    var_cmp25 = (var_13 < 11);
    if (var_cmp25) goto lbl_for_body27; else goto lbl_for_end57;
    lbl_for_body27:;
    var_14 = var_i;
    var_sub = (var_14 - 1);
    var_15 = var_j;
    var_mul28 = (var_15 * 12);
    var_add29 = (var_sub + var_mul28);
    var_idxprom30 = var_add29;
    var_arrayidx31 = (& b[var_idxprom30]);
    var_16 = *var_arrayidx31;
    var_17 = var_i;
    var_add32 = (var_17 + 1);
    var_18 = var_j;
    var_mul33 = (var_18 * 12);
    var_add34 = (var_add32 + var_mul33);
    var_idxprom35 = var_add34;
    var_arrayidx36 = (& b[var_idxprom35]);
    var_19 = *var_arrayidx36;
    var_add37 = (var_16 + var_19);
    var_20 = var_i;
    var_21 = var_j;
    var_add38 = (var_20 + var_21);
    var_sub39 = (var_add38 - 12);
    var_idxprom40 = var_sub39;
    var_arrayidx41 = (& b[var_idxprom40]);
    var_22 = *var_arrayidx41;
    var_add42 = (var_add37 + var_22);
    var_23 = var_i;
    var_24 = var_j;
    var_add43 = (var_23 + var_24);
    var_add44 = (var_add43 + 12);
    var_idxprom45 = var_add44;
    var_arrayidx46 = (& b[var_idxprom45]);
    var_25 = *var_arrayidx46;
    var_add47 = (var_add42 + var_25);
    var_conv48 = var_add47;
    var_mul49 = (0.25 * var_conv48);
    var_conv50 = var_mul49;
    var_26 = var_i;
    var_27 = var_j;
    var_mul51 = (var_27 * 12);
    var_add52 = (var_26 + var_mul51);
    var_idxprom53 = var_add52;
    var_arrayidx54 = (& a[var_idxprom53]);
    *var_arrayidx54 = var_conv50;
    goto lbl_for_inc55;
    lbl_for_inc55:;
    var_28 = var_j;
    var_inc56 = (var_28 + 1);
    var_j = var_inc56;
    goto lbl_for_cond24;
    lbl_for_end57:;
    goto lbl_for_inc58;
    lbl_for_inc58:;
    var_29 = var_i;
    var_inc59 = (var_29 + 1);
    var_i = var_inc59;
    goto lbl_for_cond20;
    lbl_for_end60:;
    var_i = 0;
    goto lbl_for_cond61;
    lbl_for_cond61:;
    var_30 = var_i;
    var_cmp62 = (var_30 < 11);
    if (var_cmp62) goto lbl_for_body64; else goto lbl_for_end82;
    lbl_for_body64:;
    var_j = 0;
    goto lbl_for_cond65;
    lbl_for_cond65:;
    var_31 = var_j;
    var_cmp66 = (var_31 < 11);
    if (var_cmp66) goto lbl_for_body68; else goto lbl_for_end79;
    lbl_for_body68:;
    var_32 = var_i;
    var_33 = var_j;
    var_mul69 = (var_33 * 12);
    var_add70 = (var_32 + var_mul69);
    var_idxprom71 = var_add70;
    var_arrayidx72 = (& a[var_idxprom71]);
    var_34 = *var_arrayidx72;
    var_35 = var_i;
    var_36 = var_j;
    var_mul73 = (var_36 * 12);
    var_add74 = (var_35 + var_mul73);
    var_idxprom75 = var_add74;
    var_arrayidx76 = (& b[var_idxprom75]);
    *var_arrayidx76 = var_34;
    goto lbl_for_inc77;
    lbl_for_inc77:;
    var_37 = var_j;
    var_inc78 = (var_37 + 1);
    var_j = var_inc78;
    goto lbl_for_cond65;
    lbl_for_end79:;
    goto lbl_for_inc80;
    lbl_for_inc80:;
    var_38 = var_i;
    var_inc81 = (var_38 + 1);
    var_i = var_inc81;
    goto lbl_for_cond61;
    lbl_for_end82:;
    var_39 = b[78];
    var_call = printf((& str[0]), var_39);
    return 0;
}
