#include <stdio.h>
#include <stdlib.h>

/* func decls begin */
void init_nbr ();
int getinput ();
void moving (int var_size);
/* func decls end */

  /* Ast::Scope prog: 10 symbols, 4 children */
  int magic = 35;
  int nbr_5[5];
  char str[3] = "%d";
  char str1[45] = "I need a non-negative number less than 100: ";
  int V[100];
  char str2[56] = "Please input the size of the vector to be transformed: ";
  char str3[18] = "Original vector:\n";
  char str4[4] = "%d\n";
  char str5[2] = "\n";
  char str6[21] = "Moving edge vector:\n";

void init_nbr (){
    /* Ast::Block init_nbr body: 1 symbols, 8 children */
    int var_reg2mem_alloca_point;

    lbl_entry:;
    var_reg2mem_alloca_point = 0;
    nbr_5[0] = -3;
    nbr_5[1] = 12;
    nbr_5[2] = 17;
    nbr_5[3] = 12;
    nbr_5[4] = -3;
    return;
}
int getinput (){
    /* Ast::Block getinput body: 11 symbols, 32 children */
    int var_a;
    int var_reg2mem_alloca_point;
    int var_0;
    int var_cmp;
    int var_call;
    int var_1;
    int var_cmp1;
    int var_2;
    int var_cmp2;
    int var_call3;
    int var_3;

    lbl_entry:;
    var_reg2mem_alloca_point = 0;
    var_a = -1;
    goto lbl_while_cond;
    lbl_while_cond:;
    var_0 = var_a;
    var_cmp = (0 >= var_0);
    if (var_cmp) goto lbl_while_body; else goto lbl_while_end;
    lbl_while_body:;
    var_call = __isoc99_scanf((& str[0]), (& var_a));
    var_1 = var_a;
    var_cmp1 = (0 >= var_1);
    if (var_cmp1) goto lbl_while_body_if_then_crit_edge; else goto lbl_lor_lhs_false;
    lbl_while_body_if_then_crit_edge:;
    goto lbl_if_then;
    lbl_lor_lhs_false:;
    var_2 = var_a;
    var_cmp2 = (var_2 >= 100);
    if (var_cmp2) goto lbl_lor_lhs_false_if_then_crit_edge; else goto lbl_lor_lhs_false_if_end_crit_edge;
    lbl_lor_lhs_false_if_end_crit_edge:;
    goto lbl_if_end;
    lbl_lor_lhs_false_if_then_crit_edge:;
    goto lbl_if_then;
    lbl_if_then:;
    var_call3 = printf((& str1[0]));
    var_a = -1;
    goto lbl_if_end;
    lbl_if_end:;
    goto lbl_while_cond;
    lbl_while_end:;
    var_3 = var_a;
    return var_3;
}
void moving (int var_size){
    /* Ast::Block moving body: 35 symbols, 57 children */
    int var_size_addr;
    int var_i;
    int var_j;
    int var_temp;
    int var_reg2mem_alloca_point;
    int var_0;
    int var_1;
    int var_sub;
    int var_cmp;
    int var_2;
    int var_cmp2;
    int var_3;
    int var_4;
    int var_add;
    long long var_idxprom;
    int *var_arrayidx;
    int var_5;
    int var_6;
    int var_add4;
    long long var_idxprom5;
    int *var_arrayidx6;
    int var_7;
    int var_mul;
    int var_8;
    int var_add7;
    int var_9;
    int var_inc;
    int var_10;
    int var_11;
    int var_div;
    int var_12;
    long long var_idxprom8;
    int *var_arrayidx9;
    int var_13;
    int var_inc11;

    lbl_entry:;
    var_reg2mem_alloca_point = 0;
    var_size_addr = var_size;
    var_i = 2;
    goto lbl_for_cond;
    lbl_for_cond:;
    var_0 = var_i;
    var_1 = var_size_addr;
    var_sub = (var_1 - 2);
    var_cmp = (var_0 < var_sub);
    if (var_cmp) goto lbl_for_body; else goto lbl_for_end12;
    lbl_for_body:;
    var_temp = 0;
    var_j = -2;
    goto lbl_for_cond1;
    lbl_for_cond1:;
    var_2 = var_j;
    var_cmp2 = (var_2 < 3);
    if (var_cmp2) goto lbl_for_body3; else goto lbl_for_end;
    lbl_for_body3:;
    var_3 = var_i;
    var_4 = var_j;
    var_add = (var_3 + var_4);
    var_idxprom = var_add;
    var_arrayidx = (& V[var_idxprom]);
    var_5 = *var_arrayidx;
    var_6 = var_j;
    var_add4 = (var_6 + 2);
    var_idxprom5 = var_add4;
    var_arrayidx6 = (& nbr_5[var_idxprom5]);
    var_7 = *var_arrayidx6;
    var_mul = (var_5 * var_7);
    var_8 = var_temp;
    var_add7 = (var_8 + var_mul);
    var_temp = var_add7;
    goto lbl_for_inc;
    lbl_for_inc:;
    var_9 = var_j;
    var_inc = (var_9 + 1);
    var_j = var_inc;
    goto lbl_for_cond1;
    lbl_for_end:;
    var_10 = var_temp;
    var_11 = magic;
    var_div = (var_10 / var_11);
    var_12 = var_i;
    var_idxprom8 = var_12;
    var_arrayidx9 = (& V[var_idxprom8]);
    *var_arrayidx9 = var_div;
    goto lbl_for_inc10;
    lbl_for_inc10:;
    var_13 = var_i;
    var_inc11 = (var_13 + 1);
    var_i = var_inc11;
    goto lbl_for_cond;
    lbl_for_end12:;
    return;
}
int main (){
    /* Ast::Block main body: 42 symbols, 76 children */
    int var_retval;
    int var_size;
    int var_i;
    int var_reg2mem_alloca_point;
    int var_call;
    int var_call1;
    int var_0;
    int var_1;
    int var_cmp;
    int var_call2;
    int var_rem;
    int var_2;
    long long var_idxprom;
    int *var_arrayidx;
    int var_3;
    int var_inc;
    int var_call3;
    int var_4;
    int var_5;
    int var_cmp5;
    int var_6;
    long long var_idxprom7;
    int *var_arrayidx8;
    int var_7;
    int var_call9;
    int var_8;
    int var_inc11;
    int var_call13;
    int var_9;
    int var_call14;
    int var_10;
    int var_11;
    int var_cmp16;
    int var_12;
    long long var_idxprom18;
    int *var_arrayidx19;
    int var_13;
    int var_call20;
    int var_14;
    int var_inc22;
    int var_call24;
    int var_15;

    lbl_entry:;
    var_reg2mem_alloca_point = 0;
    var_retval = 0;
    var_call = printf((& str2[0]));
    var_call1 = getinput();
    var_size = var_call1;
    var_i = 0;
    goto lbl_for_cond;
    lbl_for_cond:;
    var_0 = var_i;
    var_1 = var_size;
    var_cmp = (var_0 < var_1);
    if (var_cmp) goto lbl_for_body; else goto lbl_for_end;
    lbl_for_body:;
    var_call2 = rand();
    var_rem = (var_call2 % 100);
    var_2 = var_i;
    var_idxprom = var_2;
    var_arrayidx = (& V[var_idxprom]);
    *var_arrayidx = var_rem;
    goto lbl_for_inc;
    lbl_for_inc:;
    var_3 = var_i;
    var_inc = (var_3 + 1);
    var_i = var_inc;
    goto lbl_for_cond;
    lbl_for_end:;
    var_call3 = printf((& str3[0]));
    var_i = 0;
    goto lbl_for_cond4;
    lbl_for_cond4:;
    var_4 = var_i;
    var_5 = var_size;
    var_cmp5 = (var_4 < var_5);
    if (var_cmp5) goto lbl_for_body6; else goto lbl_for_end12;
    lbl_for_body6:;
    var_6 = var_i;
    var_idxprom7 = var_6;
    var_arrayidx8 = (& V[var_idxprom7]);
    var_7 = *var_arrayidx8;
    var_call9 = printf((& str4[0]), var_7);
    goto lbl_for_inc10;
    lbl_for_inc10:;
    var_8 = var_i;
    var_inc11 = (var_8 + 1);
    var_i = var_inc11;
    goto lbl_for_cond4;
    lbl_for_end12:;
    var_call13 = printf((& str5[0]));
    init_nbr();
    var_9 = var_size;
    moving(var_9);
    var_call14 = printf((& str6[0]));
    var_i = 0;
    goto lbl_for_cond15;
    lbl_for_cond15:;
    var_10 = var_i;
    var_11 = var_size;
    var_cmp16 = (var_10 < var_11);
    if (var_cmp16) goto lbl_for_body17; else goto lbl_for_end23;
    lbl_for_body17:;
    var_12 = var_i;
    var_idxprom18 = var_12;
    var_arrayidx19 = (& V[var_idxprom18]);
    var_13 = *var_arrayidx19;
    var_call20 = printf((& str4[0]), var_13);
    goto lbl_for_inc21;
    lbl_for_inc21:;
    var_14 = var_i;
    var_inc22 = (var_14 + 1);
    var_i = var_inc22;
    goto lbl_for_cond15;
    lbl_for_end23:;
    var_call24 = printf((& str5[0]));
    var_15 = var_retval;
    return var_15;
}
