#include <stdio.h>
#include <stdlib.h>

/* func decls begin */
int getinput ();
/* func decls end */

  /* Ast::Scope prog: 4 symbols, 2 children */
  char str[3] = "%d";
  char str1[45] = "I need a non-negative number less than 100: ";
  char str2[55] = "Please give the size of the vectors to be multiplied: ";
  char str3[3] = "0\n";

int getinput (){
    /* Ast::Block getinput body: 11 symbols, 32 children */
    int var_a;
    int var_reg2mem_alloca_point;
    int var_0;
    int var_cmp;
    int var_call;
    int var_1;
    int var_cmp1;
    int var_2;
    int var_cmp2;
    int var_call3;
    int var_3;

    lbl_entry:;
    var_reg2mem_alloca_point = 0;
    var_a = -1;
    goto lbl_while_cond;
    lbl_while_cond:;
    var_0 = var_a;
    var_cmp = (0 >= var_0);
    if (var_cmp) goto lbl_while_body; else goto lbl_while_end;
    lbl_while_body:;
    var_call = __isoc99_scanf((& str[0]), (& var_a));
    var_1 = var_a;
    var_cmp1 = (0 >= var_1);
    if (var_cmp1) goto lbl_while_body_if_then_crit_edge; else goto lbl_lor_lhs_false;
    lbl_while_body_if_then_crit_edge:;
    goto lbl_if_then;
    lbl_lor_lhs_false:;
    var_2 = var_a;
    var_cmp2 = (var_2 >= 100);
    if (var_cmp2) goto lbl_lor_lhs_false_if_then_crit_edge; else goto lbl_lor_lhs_false_if_end_crit_edge;
    lbl_lor_lhs_false_if_end_crit_edge:;
    goto lbl_if_end;
    lbl_lor_lhs_false_if_then_crit_edge:;
    goto lbl_if_then;
    lbl_if_then:;
    var_call3 = printf((& str1[0]));
    var_a = -1;
    goto lbl_if_end;
    lbl_if_end:;
    goto lbl_while_cond;
    lbl_while_end:;
    var_3 = var_a;
    return var_3;
}
int main (){
    /* Ast::Block main body: 62 symbols, 95 children */
    int var_retval;
    int var_A[100];
    int var_B[100];
    int var_size;
    int var_i;
    int var_j;
    int var_result;
    int var_reg2mem_alloca_point;
    int var_call;
    int var_call1;
    int *var_arrayidx;
    int var_0;
    int var_1;
    int var_cmp;
    int var_2;
    int var_sub;
    long long var_idxprom;
    int *var_arrayidx2;
    int var_3;
    int var_4;
    int var_5;
    int var_mul;
    int var_add;
    int var_6;
    long long var_idxprom3;
    int *var_arrayidx4;
    int var_7;
    int var_inc;
    int *var_arrayidx5;
    int var_8;
    int var_9;
    int var_cmp7;
    int var_10;
    int var_11;
    int var_sub9;
    long long var_idxprom10;
    int *var_arrayidx11;
    int var_12;
    int var_add12;
    int var_13;
    long long var_idxprom13;
    int *var_arrayidx14;
    int var_14;
    int var_inc16;
    int var_15;
    int var_16;
    int var_cmp19;
    int var_17;
    long long var_idxprom21;
    int *var_arrayidx22;
    int var_18;
    int var_19;
    long long var_idxprom23;
    int *var_arrayidx24;
    int var_20;
    int var_mul25;
    int var_21;
    int var_add26;
    int var_22;
    int var_inc28;
    int var_call30;
    int var_23;

    lbl_entry:;
    var_reg2mem_alloca_point = 0;
    var_retval = 0;
    var_call = printf((& str2[0]));
    var_call1 = getinput();
    var_size = var_call1;
    var_arrayidx = (& var_A[0]);
    *var_arrayidx = 0;
    var_i = 1;
    goto lbl_for_cond;
    lbl_for_cond:;
    var_0 = var_i;
    var_1 = var_size;
    var_cmp = (var_0 < var_1);
    if (var_cmp) goto lbl_for_body; else goto lbl_for_end;
    lbl_for_body:;
    var_2 = var_i;
    var_sub = (var_2 - 1);
    var_idxprom = var_sub;
    var_arrayidx2 = (& var_A[var_idxprom]);
    var_3 = *var_arrayidx2;
    var_4 = var_i;
    var_5 = var_i;
    var_mul = (var_4 * var_5);
    var_add = (var_3 + var_mul);
    var_6 = var_i;
    var_idxprom3 = var_6;
    var_arrayidx4 = (& var_A[var_idxprom3]);
    *var_arrayidx4 = var_add;
    goto lbl_for_inc;
    lbl_for_inc:;
    var_7 = var_i;
    var_inc = (var_7 + 1);
    var_i = var_inc;
    goto lbl_for_cond;
    lbl_for_end:;
    var_arrayidx5 = (& var_B[0]);
    *var_arrayidx5 = 0;
    var_i = 1;
    goto lbl_for_cond6;
    lbl_for_cond6:;
    var_8 = var_i;
    var_9 = var_size;
    var_cmp7 = (var_8 < var_9);
    if (var_cmp7) goto lbl_for_body8; else goto lbl_for_end17;
    lbl_for_body8:;
    var_10 = var_i;
    var_11 = var_i;
    var_sub9 = (var_11 - 1);
    var_idxprom10 = var_sub9;
    var_arrayidx11 = (& var_B[var_idxprom10]);
    var_12 = *var_arrayidx11;
    var_add12 = (var_10 + var_12);
    var_13 = var_i;
    var_idxprom13 = var_13;
    var_arrayidx14 = (& var_B[var_idxprom13]);
    *var_arrayidx14 = var_add12;
    goto lbl_for_inc15;
    lbl_for_inc15:;
    var_14 = var_i;
    var_inc16 = (var_14 + 1);
    var_i = var_inc16;
    goto lbl_for_cond6;
    lbl_for_end17:;
    var_result = 0;
    var_i = 0;
    goto lbl_for_cond18;
    lbl_for_cond18:;
    var_15 = var_i;
    var_16 = var_size;
    var_cmp19 = (var_15 < var_16);
    if (var_cmp19) goto lbl_for_body20; else goto lbl_for_end29;
    lbl_for_body20:;
    var_17 = var_i;
    var_idxprom21 = var_17;
    var_arrayidx22 = (& var_A[var_idxprom21]);
    var_18 = *var_arrayidx22;
    var_19 = var_i;
    var_idxprom23 = var_19;
    var_arrayidx24 = (& var_B[var_idxprom23]);
    var_20 = *var_arrayidx24;
    var_mul25 = (var_18 * var_20);
    var_21 = var_result;
    var_add26 = (var_21 + var_mul25);
    var_result = var_add26;
    goto lbl_for_inc27;
    lbl_for_inc27:;
    var_22 = var_i;
    var_inc28 = (var_22 + 1);
    var_i = var_inc28;
    goto lbl_for_cond18;
    lbl_for_end29:;
    var_call30 = printf((& str3[0]));
    var_23 = var_retval;
    return var_23;
}
