#include <stdio.h>
#include <stdlib.h>

/* func decls begin */
void insertSort (int var_lb, int var_ub);
void fill (int var_lb, int var_ub);
/* func decls end */

  /* Ast::Scope prog: 3 symbols, 3 children */
  int data[30];
  char str[10] = "results:\n";
  char str1[8] = "%d: %d\n";

void insertSort (int var_lb, int var_ub){
    /* Ast::Block insertSort body: 47 symbols, 76 children */
    int var_lb_addr;
    int var_ub_addr;
    int var_t;
    int var_i;
    int var_j;
    char var_cmp5_reg2mem;
    char var__reg2mem;
    int var_reg2mem_alloca_point;
    int var_0;
    int var_add;
    int var_1;
    int var_2;
    int var_cmp;
    int var_3;
    long long var_idxprom;
    int *var_arrayidx;
    int var_4;
    int var_5;
    int var_sub;
    int var_6;
    int var_7;
    int var_cmp2;
    int var_8;
    long long var_idxprom3;
    int *var_arrayidx4;
    int var_9;
    int var_10;
    int var_cmp5;
    char var_cmp5_reload;
    char var__reload;
    int var_11;
    long long var_idxprom7;
    int *var_arrayidx8;
    int var_12;
    int var_13;
    int var_add9;
    long long var_idxprom10;
    int *var_arrayidx11;
    int var_14;
    int var_dec;
    int var_15;
    int var_16;
    int var_add12;
    long long var_idxprom13;
    int *var_arrayidx14;
    int var_17;
    int var_inc;

    lbl_entry:;
    var_reg2mem_alloca_point = 0;
    var_lb_addr = var_lb;
    var_ub_addr = var_ub;
    var_0 = var_lb_addr;
    var_add = (var_0 + 1);
    var_i = var_add;
    goto lbl_for_cond;
    lbl_for_cond:;
    var_1 = var_i;
    var_2 = var_ub_addr;
    var_cmp = (var_1 <= var_2);
    if (var_cmp) goto lbl_for_body; else goto lbl_for_end16;
    lbl_for_body:;
    var_3 = var_i;
    var_idxprom = var_3;
    var_arrayidx = (& data[var_idxprom]);
    var_4 = *var_arrayidx;
    var_t = var_4;
    var_5 = var_i;
    var_sub = (var_5 - 1);
    var_j = var_sub;
    goto lbl_for_cond1;
    lbl_for_cond1:;
    var_6 = var_j;
    var_7 = var_lb_addr;
    var_cmp2 = (var_6 >= var_7);
    if (var_cmp2) goto lbl_land_rhs; else goto lbl_for_cond1_land_end_crit_edge;
    lbl_for_cond1_land_end_crit_edge:;
    var__reg2mem = 0;
    goto lbl_land_end;
    lbl_land_rhs:;
    var_8 = var_j;
    var_idxprom3 = var_8;
    var_arrayidx4 = (& data[var_idxprom3]);
    var_9 = *var_arrayidx4;
    var_10 = var_t;
    var_cmp5 = (var_9 >= var_10);
    var_cmp5_reg2mem = var_cmp5;
    var_cmp5_reload = var_cmp5_reg2mem;
    var__reg2mem = var_cmp5_reload;
    goto lbl_land_end;
    lbl_land_end:;
    var__reload = var__reg2mem;
    if (var__reload) goto lbl_for_body6; else goto lbl_for_end;
    lbl_for_body6:;
    var_11 = var_j;
    var_idxprom7 = var_11;
    var_arrayidx8 = (& data[var_idxprom7]);
    var_12 = *var_arrayidx8;
    var_13 = var_j;
    var_add9 = (var_13 + 1);
    var_idxprom10 = var_add9;
    var_arrayidx11 = (& data[var_idxprom10]);
    *var_arrayidx11 = var_12;
    goto lbl_for_inc;
    lbl_for_inc:;
    var_14 = var_j;
    var_dec = (var_14 + -1);
    var_j = var_dec;
    goto lbl_for_cond1;
    lbl_for_end:;
    var_15 = var_t;
    var_16 = var_j;
    var_add12 = (var_16 + 1);
    var_idxprom13 = var_add12;
    var_arrayidx14 = (& data[var_idxprom13]);
    *var_arrayidx14 = var_15;
    goto lbl_for_inc15;
    lbl_for_inc15:;
    var_17 = var_i;
    var_inc = (var_17 + 1);
    var_i = var_inc;
    goto lbl_for_cond;
    lbl_for_end16:;
    return;
}
void fill (int var_lb, int var_ub){
    /* Ast::Block fill body: 15 symbols, 28 children */
    int var_lb_addr;
    int var_ub_addr;
    int var_i;
    int var_reg2mem_alloca_point;
    int var_0;
    int var_1;
    int var_2;
    int var_cmp;
    int var_call;
    int var_rem;
    int var_3;
    long long var_idxprom;
    int *var_arrayidx;
    int var_4;
    int var_inc;

    lbl_entry:;
    var_reg2mem_alloca_point = 0;
    var_lb_addr = var_lb;
    var_ub_addr = var_ub;
    srand(1);
    var_0 = var_lb_addr;
    var_i = var_0;
    goto lbl_for_cond;
    lbl_for_cond:;
    var_1 = var_i;
    var_2 = var_ub_addr;
    var_cmp = (var_1 <= var_2);
    if (var_cmp) goto lbl_for_body; else goto lbl_for_end;
    lbl_for_body:;
    var_call = rand();
    var_rem = (var_call % 1000);
    var_3 = var_i;
    var_idxprom = var_3;
    var_arrayidx = (& data[var_idxprom]);
    *var_arrayidx = var_rem;
    goto lbl_for_inc;
    lbl_for_inc:;
    var_4 = var_i;
    var_inc = (var_4 + 1);
    var_i = var_inc;
    goto lbl_for_cond;
    lbl_for_end:;
    return;
}
int main (int var_argc, char **var_argv){
    /* Ast::Block main body: 27 symbols, 40 children */
    int var_retval;
    int var_argc_addr;
    char **var_argv_addr;
    int var_maxnum;
    int var_lb;
    int var_ub;
    int var_i;
    int var_reg2mem_alloca_point;
    int var_0;
    int var_sub;
    int var_1;
    int var_2;
    int var_3;
    int var_4;
    int var_call;
    int var_5;
    int var_6;
    int var_7;
    int var_cmp;
    int var_8;
    int var_9;
    long long var_idxprom;
    int *var_arrayidx;
    int var_10;
    int var_call1;
    int var_11;
    int var_inc;

    lbl_entry:;
    var_reg2mem_alloca_point = 0;
    var_retval = 0;
    var_argc_addr = var_argc;
    var_argv_addr = var_argv;
    var_maxnum = 30;
    var_lb = 0;
    var_0 = var_maxnum;
    var_sub = (var_0 - 1);
    var_ub = var_sub;
    var_1 = var_lb;
    var_2 = var_ub;
    fill(var_1, var_2);
    var_3 = var_lb;
    var_4 = var_ub;
    insertSort(var_3, var_4);
    var_call = printf((& str[0]));
    var_5 = var_lb;
    var_i = var_5;
    goto lbl_for_cond;
    lbl_for_cond:;
    var_6 = var_i;
    var_7 = var_ub;
    var_cmp = (var_6 <= var_7);
    if (var_cmp) goto lbl_for_body; else goto lbl_for_end;
    lbl_for_body:;
    var_8 = var_i;
    var_9 = var_i;
    var_idxprom = var_9;
    var_arrayidx = (& data[var_idxprom]);
    var_10 = *var_arrayidx;
    var_call1 = printf((& str1[0]), var_8, var_10);
    goto lbl_for_inc;
    lbl_for_inc:;
    var_11 = var_i;
    var_inc = (var_11 + 1);
    var_i = var_inc;
    goto lbl_for_cond;
    lbl_for_end:;
    return 0;
}
