#include <stdio.h>
#include <stdlib.h>

/* func decls begin */
void populate_arrays ();
void print_arrays ();
/* func decls end */

  /* Ast::Scope prog: 10 symbols, 3 children */
  int array_1[16];
  int array_2[16];
  int array_3[16];
  int array_4[16];
  char str[10] = "Array_1:\n";
  char str1[4] = "%d\n";
  char str2[11] = "\nArray_2:\n";
  char str3[11] = "\nArray_3:\n";
  char str4[11] = "\nArray_4:\n";
  char str5[2] = "\n";

void populate_arrays (){
    /* Ast::Block populate_arrays body: 1 symbols, 67 children */
    int var_reg2mem_alloca_point;

    lbl_entry:;
    var_reg2mem_alloca_point = 0;
    array_1[0] = 0;
    array_2[0] = 15;
    array_3[0] = 5;
    array_4[0] = 13;
    array_1[1] = 1;
    array_2[1] = 14;
    array_3[1] = 5;
    array_4[1] = 9;
    array_1[2] = 2;
    array_2[2] = 13;
    array_3[2] = 5;
    array_4[2] = 12;
    array_1[3] = 3;
    array_2[3] = 12;
    array_3[3] = 5;
    array_4[3] = 1;
    array_1[4] = 4;
    array_2[4] = 11;
    array_3[4] = 5;
    array_4[4] = 0;
    array_1[5] = 5;
    array_2[5] = 10;
    array_3[5] = 5;
    array_4[5] = 14;
    array_1[6] = 6;
    array_2[6] = 9;
    array_3[6] = 5;
    array_4[6] = 3;
    array_1[7] = 7;
    array_2[7] = 8;
    array_3[7] = 5;
    array_4[7] = 2;
    array_1[8] = 8;
    array_2[8] = 7;
    array_3[8] = 5;
    array_4[8] = 11;
    array_1[9] = 9;
    array_2[9] = 6;
    array_3[9] = 5;
    array_4[9] = 8;
    array_1[10] = 10;
    array_2[10] = 5;
    array_3[10] = 5;
    array_4[10] = 6;
    array_1[11] = 11;
    array_2[11] = 4;
    array_3[11] = 5;
    array_4[11] = 4;
    array_1[12] = 12;
    array_2[12] = 3;
    array_3[12] = 5;
    array_4[12] = 5;
    array_1[13] = 13;
    array_2[13] = 2;
    array_3[13] = 5;
    array_4[13] = 10;
    array_1[14] = 14;
    array_2[14] = 1;
    array_3[14] = 5;
    array_4[14] = 7;
    array_1[15] = 15;
    array_2[15] = 0;
    array_3[15] = 5;
    array_4[15] = 15;
    return;
}
void print_arrays (){
    /* Ast::Block print_arrays body: 48 symbols, 81 children */
    int var_idx;
    int var_bound;
    int var_reg2mem_alloca_point;
    int var_call;
    int var_0;
    int var_1;
    int var_cmp;
    int var_2;
    long long var_idxprom;
    int *var_arrayidx;
    int var_3;
    int var_call1;
    int var_4;
    int var_add;
    int var_call2;
    int var_5;
    int var_6;
    int var_cmp4;
    int var_7;
    long long var_idxprom6;
    int *var_arrayidx7;
    int var_8;
    int var_call8;
    int var_9;
    int var_add9;
    int var_call11;
    int var_10;
    int var_11;
    int var_cmp13;
    int var_12;
    long long var_idxprom15;
    int *var_arrayidx16;
    int var_13;
    int var_call17;
    int var_14;
    int var_add18;
    int var_call20;
    int var_15;
    int var_16;
    int var_cmp22;
    int var_17;
    long long var_idxprom24;
    int *var_arrayidx25;
    int var_18;
    int var_call26;
    int var_19;
    int var_add27;
    int var_call29;

    lbl_entry:;
    var_reg2mem_alloca_point = 0;
    var_bound = 16;
    var_call = printf((& str[0]));
    var_idx = 0;
    goto lbl_while_cond;
    lbl_while_cond:;
    var_0 = var_idx;
    var_1 = var_bound;
    var_cmp = (var_0 < var_1);
    if (var_cmp) goto lbl_while_body; else goto lbl_while_end;
    lbl_while_body:;
    var_2 = var_idx;
    var_idxprom = var_2;
    var_arrayidx = (& array_1[var_idxprom]);
    var_3 = *var_arrayidx;
    var_call1 = printf((& str1[0]), var_3);
    var_4 = var_idx;
    var_add = (var_4 + 1);
    var_idx = var_add;
    goto lbl_while_cond;
    lbl_while_end:;
    var_call2 = printf((& str2[0]));
    var_idx = 0;
    goto lbl_while_cond3;
    lbl_while_cond3:;
    var_5 = var_idx;
    var_6 = var_bound;
    var_cmp4 = (var_5 < var_6);
    if (var_cmp4) goto lbl_while_body5; else goto lbl_while_end10;
    lbl_while_body5:;
    var_7 = var_idx;
    var_idxprom6 = var_7;
    var_arrayidx7 = (& array_2[var_idxprom6]);
    var_8 = *var_arrayidx7;
    var_call8 = printf((& str1[0]), var_8);
    var_9 = var_idx;
    var_add9 = (var_9 + 1);
    var_idx = var_add9;
    goto lbl_while_cond3;
    lbl_while_end10:;
    var_call11 = printf((& str3[0]));
    var_idx = 0;
    goto lbl_while_cond12;
    lbl_while_cond12:;
    var_10 = var_idx;
    var_11 = var_bound;
    var_cmp13 = (var_10 < var_11);
    if (var_cmp13) goto lbl_while_body14; else goto lbl_while_end19;
    lbl_while_body14:;
    var_12 = var_idx;
    var_idxprom15 = var_12;
    var_arrayidx16 = (& array_3[var_idxprom15]);
    var_13 = *var_arrayidx16;
    var_call17 = printf((& str1[0]), var_13);
    var_14 = var_idx;
    var_add18 = (var_14 + 1);
    var_idx = var_add18;
    goto lbl_while_cond12;
    lbl_while_end19:;
    var_call20 = printf((& str4[0]));
    var_idx = 0;
    goto lbl_while_cond21;
    lbl_while_cond21:;
    var_15 = var_idx;
    var_16 = var_bound;
    var_cmp22 = (var_15 < var_16);
    if (var_cmp22) goto lbl_while_body23; else goto lbl_while_end28;
    lbl_while_body23:;
    var_17 = var_idx;
    var_idxprom24 = var_17;
    var_arrayidx25 = (& array_4[var_idxprom24]);
    var_18 = *var_arrayidx25;
    var_call26 = printf((& str1[0]), var_18);
    var_19 = var_idx;
    var_add27 = (var_19 + 1);
    var_idx = var_add27;
    goto lbl_while_cond21;
    lbl_while_end28:;
    var_call29 = printf((& str5[0]));
    return;
}
int main (){
    /* Ast::Block main body: 138 symbols, 206 children */
    int var_retval;
    int var_idx;
    int var_bound;
    int var_temp;
    int var_reg2mem_alloca_point;
    int var_0;
    int var_1;
    int var_sub;
    int var_cmp;
    int var_2;
    long long var_idxprom;
    int *var_arrayidx;
    int var_3;
    int var_4;
    int var_add;
    long long var_idxprom1;
    int *var_arrayidx2;
    int var_5;
    int var_cmp3;
    int var_6;
    long long var_idxprom4;
    int *var_arrayidx5;
    int var_7;
    int var_8;
    int var_add6;
    long long var_idxprom7;
    int *var_arrayidx8;
    int var_9;
    int var_10;
    long long var_idxprom9;
    int *var_arrayidx10;
    int var_11;
    int var_12;
    int var_add11;
    long long var_idxprom12;
    int *var_arrayidx13;
    int var_13;
    int var_add14;
    int var_14;
    int var_15;
    int var_sub16;
    int var_cmp17;
    int var_16;
    long long var_idxprom19;
    int *var_arrayidx20;
    int var_17;
    int var_18;
    int var_add21;
    long long var_idxprom22;
    int *var_arrayidx23;
    int var_19;
    int var_cmp24;
    int var_20;
    long long var_idxprom26;
    int *var_arrayidx27;
    int var_21;
    int var_22;
    int var_add28;
    long long var_idxprom29;
    int *var_arrayidx30;
    int var_23;
    int var_24;
    long long var_idxprom31;
    int *var_arrayidx32;
    int var_25;
    int var_26;
    int var_add33;
    long long var_idxprom34;
    int *var_arrayidx35;
    int var_27;
    int var_add37;
    int var_28;
    int var_29;
    int var_sub40;
    int var_cmp41;
    int var_30;
    long long var_idxprom43;
    int *var_arrayidx44;
    int var_31;
    int var_32;
    int var_add45;
    long long var_idxprom46;
    int *var_arrayidx47;
    int var_33;
    int var_cmp48;
    int var_34;
    long long var_idxprom50;
    int *var_arrayidx51;
    int var_35;
    int var_36;
    int var_add52;
    long long var_idxprom53;
    int *var_arrayidx54;
    int var_37;
    int var_38;
    long long var_idxprom55;
    int *var_arrayidx56;
    int var_39;
    int var_40;
    int var_add57;
    long long var_idxprom58;
    int *var_arrayidx59;
    int var_41;
    int var_add61;
    int var_42;
    int var_43;
    int var_sub64;
    int var_cmp65;
    int var_44;
    long long var_idxprom67;
    int *var_arrayidx68;
    int var_45;
    int var_46;
    int var_add69;
    long long var_idxprom70;
    int *var_arrayidx71;
    int var_47;
    int var_cmp72;
    int var_48;
    long long var_idxprom74;
    int *var_arrayidx75;
    int var_49;
    int var_50;
    int var_add76;
    long long var_idxprom77;
    int *var_arrayidx78;
    int var_51;
    int var_52;
    long long var_idxprom79;
    int *var_arrayidx80;
    int var_53;
    int var_54;
    int var_add81;
    long long var_idxprom82;
    int *var_arrayidx83;
    int var_55;
    int var_add85;
    int var_56;

    lbl_entry:;
    var_reg2mem_alloca_point = 0;
    var_retval = 0;
    var_bound = 16;
    populate_arrays();
    print_arrays();
    var_bound = 16;
    var_idx = 0;
    goto lbl_while_cond;
    lbl_while_cond:;
    var_0 = var_idx;
    var_1 = var_bound;
    var_sub = (var_1 - 1);
    var_cmp = (var_0 < var_sub);
    if (var_cmp) goto lbl_while_body; else goto lbl_while_end;
    lbl_while_body:;
    var_2 = var_idx;
    var_idxprom = var_2;
    var_arrayidx = (& array_1[var_idxprom]);
    var_3 = *var_arrayidx;
    var_4 = var_idx;
    var_add = (var_4 + 1);
    var_idxprom1 = var_add;
    var_arrayidx2 = (& array_1[var_idxprom1]);
    var_5 = *var_arrayidx2;
    var_cmp3 = (var_3 >= var_5);
    if (var_cmp3) goto lbl_if_then; else goto lbl_if_end;
    lbl_if_then:;
    var_6 = var_idx;
    var_idxprom4 = var_6;
    var_arrayidx5 = (& array_1[var_idxprom4]);
    var_7 = *var_arrayidx5;
    var_temp = var_7;
    var_8 = var_idx;
    var_add6 = (var_8 + 1);
    var_idxprom7 = var_add6;
    var_arrayidx8 = (& array_1[var_idxprom7]);
    var_9 = *var_arrayidx8;
    var_10 = var_idx;
    var_idxprom9 = var_10;
    var_arrayidx10 = (& array_1[var_idxprom9]);
    *var_arrayidx10 = var_9;
    var_11 = var_temp;
    var_12 = var_idx;
    var_add11 = (var_12 + 1);
    var_idxprom12 = var_add11;
    var_arrayidx13 = (& array_1[var_idxprom12]);
    *var_arrayidx13 = var_11;
    var_idx = 0;
    goto lbl_while_cond;
    lbl_if_end:;
    var_13 = var_idx;
    var_add14 = (var_13 + 1);
    var_idx = var_add14;
    goto lbl_while_cond;
    lbl_while_end:;
    var_idx = 0;
    goto lbl_while_cond15;
    lbl_while_cond15:;
    var_14 = var_idx;
    var_15 = var_bound;
    var_sub16 = (var_15 - 1);
    var_cmp17 = (var_14 < var_sub16);
    if (var_cmp17) goto lbl_while_body18; else goto lbl_while_end38;
    lbl_while_body18:;
    var_16 = var_idx;
    var_idxprom19 = var_16;
    var_arrayidx20 = (& array_2[var_idxprom19]);
    var_17 = *var_arrayidx20;
    var_18 = var_idx;
    var_add21 = (var_18 + 1);
    var_idxprom22 = var_add21;
    var_arrayidx23 = (& array_2[var_idxprom22]);
    var_19 = *var_arrayidx23;
    var_cmp24 = (var_17 >= var_19);
    if (var_cmp24) goto lbl_if_then25; else goto lbl_if_end36;
    lbl_if_then25:;
    var_20 = var_idx;
    var_idxprom26 = var_20;
    var_arrayidx27 = (& array_2[var_idxprom26]);
    var_21 = *var_arrayidx27;
    var_temp = var_21;
    var_22 = var_idx;
    var_add28 = (var_22 + 1);
    var_idxprom29 = var_add28;
    var_arrayidx30 = (& array_2[var_idxprom29]);
    var_23 = *var_arrayidx30;
    var_24 = var_idx;
    var_idxprom31 = var_24;
    var_arrayidx32 = (& array_2[var_idxprom31]);
    *var_arrayidx32 = var_23;
    var_25 = var_temp;
    var_26 = var_idx;
    var_add33 = (var_26 + 1);
    var_idxprom34 = var_add33;
    var_arrayidx35 = (& array_2[var_idxprom34]);
    *var_arrayidx35 = var_25;
    var_idx = 0;
    goto lbl_while_cond15;
    lbl_if_end36:;
    var_27 = var_idx;
    var_add37 = (var_27 + 1);
    var_idx = var_add37;
    goto lbl_while_cond15;
    lbl_while_end38:;
    var_idx = 0;
    goto lbl_while_cond39;
    lbl_while_cond39:;
    var_28 = var_idx;
    var_29 = var_bound;
    var_sub40 = (var_29 - 1);
    var_cmp41 = (var_28 < var_sub40);
    if (var_cmp41) goto lbl_while_body42; else goto lbl_while_end62;
    lbl_while_body42:;
    var_30 = var_idx;
    var_idxprom43 = var_30;
    var_arrayidx44 = (& array_3[var_idxprom43]);
    var_31 = *var_arrayidx44;
    var_32 = var_idx;
    var_add45 = (var_32 + 1);
    var_idxprom46 = var_add45;
    var_arrayidx47 = (& array_3[var_idxprom46]);
    var_33 = *var_arrayidx47;
    var_cmp48 = (var_31 >= var_33);
    if (var_cmp48) goto lbl_if_then49; else goto lbl_if_end60;
    lbl_if_then49:;
    var_34 = var_idx;
    var_idxprom50 = var_34;
    var_arrayidx51 = (& array_1[var_idxprom50]);
    var_35 = *var_arrayidx51;
    var_temp = var_35;
    var_36 = var_idx;
    var_add52 = (var_36 + 1);
    var_idxprom53 = var_add52;
    var_arrayidx54 = (& array_3[var_idxprom53]);
    var_37 = *var_arrayidx54;
    var_38 = var_idx;
    var_idxprom55 = var_38;
    var_arrayidx56 = (& array_3[var_idxprom55]);
    *var_arrayidx56 = var_37;
    var_39 = var_temp;
    var_40 = var_idx;
    var_add57 = (var_40 + 1);
    var_idxprom58 = var_add57;
    var_arrayidx59 = (& array_3[var_idxprom58]);
    *var_arrayidx59 = var_39;
    var_idx = 0;
    goto lbl_while_cond39;
    lbl_if_end60:;
    var_41 = var_idx;
    var_add61 = (var_41 + 1);
    var_idx = var_add61;
    goto lbl_while_cond39;
    lbl_while_end62:;
    var_idx = 0;
    goto lbl_while_cond63;
    lbl_while_cond63:;
    var_42 = var_idx;
    var_43 = var_bound;
    var_sub64 = (var_43 - 1);
    var_cmp65 = (var_42 < var_sub64);
    if (var_cmp65) goto lbl_while_body66; else goto lbl_while_end86;
    lbl_while_body66:;
    var_44 = var_idx;
    var_idxprom67 = var_44;
    var_arrayidx68 = (& array_4[var_idxprom67]);
    var_45 = *var_arrayidx68;
    var_46 = var_idx;
    var_add69 = (var_46 + 1);
    var_idxprom70 = var_add69;
    var_arrayidx71 = (& array_4[var_idxprom70]);
    var_47 = *var_arrayidx71;
    var_cmp72 = (var_45 >= var_47);
    if (var_cmp72) goto lbl_if_then73; else goto lbl_if_end84;
    lbl_if_then73:;
    var_48 = var_idx;
    var_idxprom74 = var_48;
    var_arrayidx75 = (& array_4[var_idxprom74]);
    var_49 = *var_arrayidx75;
    var_temp = var_49;
    var_50 = var_idx;
    var_add76 = (var_50 + 1);
    var_idxprom77 = var_add76;
    var_arrayidx78 = (& array_4[var_idxprom77]);
    var_51 = *var_arrayidx78;
    var_52 = var_idx;
    var_idxprom79 = var_52;
    var_arrayidx80 = (& array_4[var_idxprom79]);
    *var_arrayidx80 = var_51;
    var_53 = var_temp;
    var_54 = var_idx;
    var_add81 = (var_54 + 1);
    var_idxprom82 = var_add81;
    var_arrayidx83 = (& array_4[var_idxprom82]);
    *var_arrayidx83 = var_53;
    var_idx = 0;
    goto lbl_while_cond63;
    lbl_if_end84:;
    var_55 = var_idx;
    var_add85 = (var_55 + 1);
    var_idx = var_add85;
    goto lbl_while_cond63;
    lbl_while_end86:;
    print_arrays();
    var_56 = var_retval;
    return var_56;
}
