#include <stdio.h>
#include <stdlib.h>

/* func decls begin */
int getinput ();
/* func decls end */

  /* Ast::Scope prog: 27 symbols, 2 children */
  char str[3] = "%d";
  char str1[31] = "I need a non-negative number: ";
  char str2[63] = "Welcome to the United States 1040 federal income tax program.\n";
  char str3[65] = "(Note: this isn't the real 1040 form. If you try to submit your\n";
  char str4[47] = "taxes this way, you'll get what you deserve!\n\n";
  char str5[60] = "Answer the following questions to determine what you owe.\n\n";
  char str6[32] = "Total wages, salary, and tips? ";
  char str7[48] = "Taxable interest (such as from bank accounts)? ";
  char str8[64] = "Unemployment compensation, qualified state tuition, and Alaska\n";
  char str9[27] = "Permanent Fund dividends? ";
  char str10[32] = "Your adjusted gross income is: ";
  char str11[4] = "%d\n";
  char str12[65] = "Enter <1> if your parents or someone else can claim you on their";
  char str13[32] = " return. \nEnter <0> otherwise: ";
  char str14[54] = "Enter <1> if you are single, <0> if you are married: ";
  char str15[57] = "Enter <1> if your spouse can be claimed as a dependant, ";
  char str16[19] = "enter <0> if not: ";
  char str17[25] = "Your taxable income is: ";
  char str18[50] = "Enter the amount of Federal income tax withheld: ";
  char str19[53] = "";
  char str20[20] = "enter 0 otherwise: ";
  char str21[55] = "OK, I'll give you a thousand dollars for your credit.\n";
  char str22[36] = "Your total tax payments amount to: ";
  char str23[30] = "Your total tax liability is: ";
  char str24[43] = "Congratulations, you get a tax refund of $";
  char str25[38] = "Bummer. You owe the IRS a check for $";
  char str26[29] = "Thank you for using ez-tax.\n";

int getinput (){
    /* Ast::Block getinput body: 9 symbols, 23 children */
    int var_inp;
    int var_reg2mem_alloca_point;
    int var_0;
    int var_cmp;
    int var_call;
    int var_1;
    int var_cmp1;
    int var_call2;
    int var_2;

    lbl_entry:;
    var_reg2mem_alloca_point = 0;
    var_inp = -1;
    goto lbl_while_cond;
    lbl_while_cond:;
    var_0 = var_inp;
    var_cmp = (0 >= var_0);
    if (var_cmp) goto lbl_while_body; else goto lbl_while_end;
    lbl_while_body:;
    var_call = __isoc99_scanf((& str[0]), (& var_inp));
    var_1 = var_inp;
    var_cmp1 = (0 >= var_1);
    if (var_cmp1) goto lbl_if_then; else goto lbl_while_body_if_end_crit_edge;
    lbl_while_body_if_end_crit_edge:;
    goto lbl_if_end;
    lbl_if_then:;
    var_call2 = printf((& str1[0]));
    goto lbl_if_end;
    lbl_if_end:;
    goto lbl_while_cond;
    lbl_while_end:;
    var_2 = var_inp;
    return var_2;
}
int main (){
    /* Ast::Block main body: 175 symbols, 283 children */
    int var_retval;
    int var_line1;
    int var_line2;
    int var_line3;
    int var_line4;
    int var_line5;
    int var_line6;
    int var_line7;
    int var_line8;
    int var_deadline11;
    int var_deadline12;
    int var_line10;
    int var_dependant;
    int var_single;
    int var_b;
    int var_c;
    int var_d;
    int var_e;
    int var_f;
    int var_g;
    int var_eic;
    int var_spousedependant;
    int var_reg2mem_alloca_point;
    int var_call;
    int var_call1;
    int var_call2;
    int var_call3;
    int var_call4;
    int var_call5;
    int var_call6;
    int var_call7;
    int var_call8;
    int var_call9;
    int var_call10;
    int var_0;
    int var_1;
    int var_add;
    int var_2;
    int var_add11;
    int var_call12;
    int var_3;
    int var_call13;
    int var_call14;
    int var_call15;
    int var_call16;
    int var_4;
    int var_cmp;
    int var_5;
    int var_6;
    int var_7;
    int var_add17;
    int var_cmp18;
    int var_8;
    int var_add20;
    int var_call21;
    int var_call22;
    int var_9;
    int var_cmp23;
    int var_10;
    int var_11;
    int var_12;
    int var_cmp26;
    int var_13;
    int var_14;
    int var_cmp29;
    int var_call31;
    int var_call32;
    int var_call33;
    int var_15;
    int var_cmp34;
    int var_16;
    int var_17;
    int var_add38;
    int var_18;
    int var_19;
    int var_cmp40;
    int var_call42;
    int var_call43;
    int var_20;
    int var_cmp44;
    int var_21;
    int var_cmp47;
    int var_22;
    int var_23;
    int var_sub;
    int var_24;
    int var_cmp51;
    int var_call54;
    int var_25;
    int var_call55;
    int var_call56;
    int var_call57;
    int var_call58;
    int var_call59;
    int var_call60;
    int var_26;
    int var_cmp61;
    int var_call63;
    int var_call65;
    int var_27;
    int var_28;
    int var_add66;
    int var_call67;
    int var_29;
    int var_mul;
    int var_add68;
    int var_div;
    int var_call69;
    int var_30;
    int var_call70;
    int var_31;
    int var_32;
    int var_add71;
    int var_33;
    int var_sub72;
    int var_cmp73;
    int var_34;
    int var_35;
    int var_add77;
    int var_36;
    int var_sub78;
    int var_cmp79;
    int var_call81;
    int var_37;
    int var_38;
    int var_add82;
    int var_39;
    int var_sub83;
    int var_call84;
    int var_40;
    int var_41;
    int var_42;
    int var_add86;
    int var_sub87;
    int var_cmp88;
    int var_call90;
    int var_43;
    int var_44;
    int var_45;
    int var_add91;
    int var_sub92;
    int var_call93;
    int var_46;
    int var_47;
    int var_48;
    int var_add95;
    int var_sub96;
    int var_cmp97;
    int var_49;
    int var_call101;
    int var_50;
    int var_51;
    int var_add102;
    int var_call103;
    int var_52;
    int var_call104;
    int var_53;
    int var_call105;
    int var_54;
    int var_call106;
    int var_55;
    int var_call107;
    int var_56;
    int var_call108;
    int var_57;
    int var_call109;
    int var_58;
    int var_59;
    int var_60;
    int var_add110;
    int var_61;
    int var_62;
    int var_add111;
    int var_call112;
    int var_63;

    lbl_entry:;
    var_reg2mem_alloca_point = 0;
    var_retval = 0;
    var_call = printf((& str2[0]));
    var_call1 = printf((& str3[0]));
    var_call2 = printf((& str4[0]));
    var_call3 = printf((& str5[0]));
    var_call4 = printf((& str6[0]));
    var_call5 = getinput();
    var_line1 = var_call5;
    var_call6 = printf((& str7[0]));
    var_call7 = getinput();
    var_line2 = var_call7;
    var_call8 = printf((& str8[0]));
    var_call9 = printf((& str9[0]));
    var_call10 = getinput();
    var_line3 = var_call10;
    var_0 = var_line1;
    var_1 = var_line2;
    var_add = (var_0 + var_1);
    var_2 = var_line3;
    var_add11 = (var_add + var_2);
    var_line4 = var_add11;
    var_call12 = printf((& str10[0]));
    var_3 = var_line4;
    var_call13 = printf((& str11[0]), var_3);
    var_call14 = printf((& str12[0]));
    var_call15 = printf((& str13[0]));
    var_call16 = getinput();
    var_dependant = var_call16;
    var_4 = var_dependant;
    var_cmp = (0 != var_4);
    if (var_cmp) goto lbl_if_then; else goto lbl_entry_if_end39_crit_edge;
    lbl_entry_if_end39_crit_edge:;
    goto lbl_if_end39;
    lbl_if_then:;
    var_b = 700;
    var_5 = var_b;
    var_c = var_5;
    var_6 = var_c;
    var_7 = var_line1;
    var_add17 = (var_7 + 250);
    var_cmp18 = (var_6 < var_add17);
    if (var_cmp18) goto lbl_if_then19; else goto lbl_if_then_if_end_crit_edge;
    lbl_if_then_if_end_crit_edge:;
    goto lbl_if_end;
    lbl_if_then19:;
    var_8 = var_line1;
    var_add20 = (var_8 + 250);
    var_c = var_add20;
    goto lbl_if_end;
    lbl_if_end:;
    var_call21 = printf((& str14[0]));
    var_call22 = getinput();
    var_single = var_call22;
    var_9 = var_single;
    var_cmp23 = (0 != var_9);
    if (var_cmp23) goto lbl_if_then24; else goto lbl_if_else;
    lbl_if_then24:;
    var_d = 7350;
    goto lbl_if_end25;
    lbl_if_else:;
    var_d = 7350;
    goto lbl_if_end25;
    lbl_if_end25:;
    var_10 = var_c;
    var_e = var_10;
    var_11 = var_e;
    var_12 = var_d;
    var_cmp26 = (var_11 >= var_12);
    if (var_cmp26) goto lbl_if_then27; else goto lbl_if_end25_if_end28_crit_edge;
    lbl_if_end25_if_end28_crit_edge:;
    goto lbl_if_end28;
    lbl_if_then27:;
    var_13 = var_d;
    var_e = var_13;
    goto lbl_if_end28;
    lbl_if_end28:;
    var_f = 0;
    var_14 = var_single;
    var_cmp29 = (var_14 == 0);
    if (var_cmp29) goto lbl_if_then30; else goto lbl_if_end28_if_end37_crit_edge;
    lbl_if_end28_if_end37_crit_edge:;
    goto lbl_if_end37;
    lbl_if_then30:;
    var_call31 = printf((& str15[0]));
    var_call32 = printf((& str16[0]));
    var_call33 = getinput();
    var_spousedependant = var_call33;
    var_15 = var_spousedependant;
    var_cmp34 = (0 == var_15);
    if (var_cmp34) goto lbl_if_then35; else goto lbl_if_then30_if_end36_crit_edge;
    lbl_if_then30_if_end36_crit_edge:;
    goto lbl_if_end36;
    lbl_if_then35:;
    var_f = 2800;
    goto lbl_if_end36;
    lbl_if_end36:;
    goto lbl_if_end37;
    lbl_if_end37:;
    var_16 = var_e;
    var_17 = var_f;
    var_add38 = (var_16 + var_17);
    var_g = var_add38;
    var_18 = var_g;
    var_line5 = var_18;
    goto lbl_if_end39;
    lbl_if_end39:;
    var_19 = var_dependant;
    var_cmp40 = (0 == var_19);
    if (var_cmp40) goto lbl_if_then41; else goto lbl_if_end39_if_end50_crit_edge;
    lbl_if_end39_if_end50_crit_edge:;
    goto lbl_if_end50;
    lbl_if_then41:;
    var_call42 = printf((& str14[0]));
    var_call43 = getinput();
    var_single = var_call43;
    var_20 = var_single;
    var_cmp44 = (0 != var_20);
    if (var_cmp44) goto lbl_if_then45; else goto lbl_if_then41_if_end46_crit_edge;
    lbl_if_then41_if_end46_crit_edge:;
    goto lbl_if_end46;
    lbl_if_then45:;
    var_line5 = 12950;
    goto lbl_if_end46;
    lbl_if_end46:;
    var_21 = var_single;
    var_cmp47 = (0 == var_21);
    if (var_cmp47) goto lbl_if_then48; else goto lbl_if_end46_if_end49_crit_edge;
    lbl_if_end46_if_end49_crit_edge:;
    goto lbl_if_end49;
    lbl_if_then48:;
    var_line5 = 7200;
    goto lbl_if_end49;
    lbl_if_end49:;
    goto lbl_if_end50;
    lbl_if_end50:;
    var_22 = var_line4;
    var_23 = var_line5;
    var_sub = (var_22 - var_23);
    var_line6 = var_sub;
    var_24 = var_line6;
    var_cmp51 = (var_24 < 0);
    if (var_cmp51) goto lbl_if_then52; else goto lbl_if_end50_if_end53_crit_edge;
    lbl_if_end50_if_end53_crit_edge:;
    goto lbl_if_end53;
    lbl_if_then52:;
    var_line6 = 0;
    goto lbl_if_end53;
    lbl_if_end53:;
    var_call54 = printf((& str17[0]));
    var_25 = var_line6;
    var_call55 = printf((& str11[0]), var_25);
    var_call56 = printf((& str18[0]));
    var_call57 = getinput();
    var_line7 = var_call57;
    var_call58 = printf((& str19[0]));
    var_call59 = printf((& str20[0]));
    var_call60 = getinput();
    var_eic = var_call60;
    var_line8 = 0;
    var_26 = var_eic;
    var_cmp61 = (0 != var_26);
    if (var_cmp61) goto lbl_if_then62; else goto lbl_if_end53_if_end64_crit_edge;
    lbl_if_end53_if_end64_crit_edge:;
    goto lbl_if_end64;
    lbl_if_then62:;
    var_call63 = printf((& str21[0]));
    var_line8 = 1000;
    goto lbl_if_end64;
    lbl_if_end64:;
    var_call65 = printf((& str22[0]));
    var_27 = var_line8;
    var_28 = var_line7;
    var_add66 = (var_27 + var_28);
    var_call67 = printf((& str11[0]), var_add66);
    var_29 = var_line6;
    var_mul = (var_29 * 28);
    var_add68 = (var_mul + 50);
    var_div = (var_add68 / 100);
    var_line10 = var_div;
    var_call69 = printf((& str23[0]));
    var_30 = var_line10;
    var_call70 = printf((& str11[0]), var_30);
    var_31 = var_line8;
    var_32 = var_line7;
    var_add71 = (var_31 + var_32);
    var_33 = var_line10;
    var_sub72 = (var_add71 - var_33);
    var_cmp73 = (var_sub72 < 0);
    if (var_cmp73) goto lbl_if_then74; else goto lbl_if_else75;
    lbl_if_then74:;
    var_deadline11 = 0;
    goto lbl_if_end76;
    lbl_if_else75:;
    var_deadline11 = 0;
    goto lbl_if_end76;
    lbl_if_end76:;
    var_34 = var_line8;
    var_35 = var_line7;
    var_add77 = (var_34 + var_35);
    var_36 = var_line10;
    var_sub78 = (var_add77 - var_36);
    var_cmp79 = (var_sub78 >= 0);
    if (var_cmp79) goto lbl_if_then80; else goto lbl_if_end76_if_end85_crit_edge;
    lbl_if_end76_if_end85_crit_edge:;
    goto lbl_if_end85;
    lbl_if_then80:;
    var_call81 = printf((& str24[0]));
    var_37 = var_line8;
    var_38 = var_line7;
    var_add82 = (var_37 + var_38);
    var_39 = var_line10;
    var_sub83 = (var_add82 - var_39);
    var_call84 = printf((& str11[0]), var_sub83);
    goto lbl_if_end85;
    lbl_if_end85:;
    var_40 = var_line10;
    var_41 = var_line8;
    var_42 = var_line7;
    var_add86 = (var_41 + var_42);
    var_sub87 = (var_40 - var_add86);
    var_cmp88 = (var_sub87 >= 0);
    if (var_cmp88) goto lbl_if_then89; else goto lbl_if_end85_if_end94_crit_edge;
    lbl_if_end85_if_end94_crit_edge:;
    goto lbl_if_end94;
    lbl_if_then89:;
    var_call90 = printf((& str25[0]));
    var_43 = var_line10;
    var_44 = var_line8;
    var_45 = var_line7;
    var_add91 = (var_44 + var_45);
    var_sub92 = (var_43 - var_add91);
    var_call93 = printf((& str11[0]), var_sub92);
    goto lbl_if_end94;
    lbl_if_end94:;
    var_46 = var_line10;
    var_47 = var_line8;
    var_48 = var_line7;
    var_add95 = (var_47 + var_48);
    var_sub96 = (var_46 - var_add95);
    var_cmp97 = (var_sub96 < 0);
    if (var_cmp97) goto lbl_if_then98; else goto lbl_if_else99;
    lbl_if_then98:;
    var_deadline12 = 0;
    goto lbl_if_end100;
    lbl_if_else99:;
    var_deadline12 = 0;
    goto lbl_if_end100;
    lbl_if_end100:;
    var_49 = var_line6;
    var_call101 = printf((& str11[0]), var_49);
    var_50 = var_line8;
    var_51 = var_line7;
    var_add102 = (var_50 + var_51);
    var_call103 = printf((& str11[0]), var_add102);
    var_52 = var_line10;
    var_call104 = printf((& str11[0]), var_52);
    var_53 = var_b;
    var_call105 = printf((& str11[0]), var_53);
    var_54 = var_e;
    var_call106 = printf((& str11[0]), var_54);
    var_55 = var_d;
    var_call107 = printf((& str11[0]), var_55);
    var_56 = var_deadline11;
    var_call108 = printf((& str11[0]), var_56);
    var_57 = var_deadline12;
    var_call109 = printf((& str11[0]), var_57);
    var_58 = var_line10;
    var_line6 = var_58;
    var_line8 = 0;
    var_line10 = 0;
    var_59 = var_b;
    var_60 = var_deadline12;
    var_add110 = (var_59 + var_60);
    var_deadline11 = var_add110;
    var_61 = var_e;
    var_62 = var_d;
    var_add111 = (var_61 + var_62);
    var_deadline12 = var_add111;
    var_call112 = printf((& str26[0]));
    var_63 = var_retval;
    return var_63;
}
